apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
type: Opaque
data:
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=
  DATABASE_URL: c3FsaXRlK2Fpb3NxbGl0ZTovLy8vZm9ybml0dXJlX2NybS5kYg==